config/routes.rb
WellerInteriorDesign::Application.routes.draw do
  resources :templates

  resources :timesheets

  resources :invoices

  resources :purchaseorders

  resources :sales

  resources :purchases

  resources :elements

  resources :estimates

  resources :rooms

  resources :jobs

  resources :clients

  resources :items

  resources :suppliers

  resources :categories

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  
  root :to => 'sessions#new', :as => :login

end

app/models/estimate.rb
class Estimate < ActiveRecord::Base

  attr_accessible :name, :room_id, :sale_id, :elements_attributes
  belongs_to :room
  has_many :elements, :inverse_of => :estimate
  accepts_nested_attributes_for :elements
  belongs_to :sale
  validates_presence_of :name,:room_id
  
#  def quantities
#    q = ""
#    self.elements.each do |element|
#      q+= "#{element.quantity}x#{element.item.supplier.name} #{element.item.name} #{element.item.code}"
#    end
#    q
#  end

  def quantity
    if self.elements.count == 1
      self.elements.first.quantity
    else
      1
    end
  end
  
  def price_ex_vat
    if self.elements.count == 1
      self.elements.first.item.price_ex_vat
    else
      self.value[0]
    end
  end
  
  def price_inc_vat
    if self.elements.count == 1
      self.elements.first.item.price_inc_vat
    else
      self.value[1]
    end
  end
  
  def value
    v = [0,0]
    self.elements.each do |element|
      evalue = element.value
      v[0] += evalue[0]
      v[1] += evalue[1]
    end
    v
  end

  def fullvalue
    e = [0,0]
    p = [0,0]
    s = [0,0]
    self.elements.each do |element|
      e[0] += element.value[0]
      e[1] += element.value[1]
      purch = element.purchase
      if purch
      p[0] += purch.quantity*purch.price_ex_vat
      p[1] += purch.quantity*purch.price_ex_vat
      end
    end
    if self.sale
    s[0] += self.sale.quantity*self.sale.price_ex_vat
    s[1] += self.sale.quantity*self.sale.price_inc_vat
    end
    [e,p,s]
  end
  
  def started
    self.elements.each do |element|
      if element.purchase
        return true
      end
    end
    return false
  end
  
  def finished
    e = self.elements.count
    if e == 0
      false
    else
      p = Estimate.where(:id => self.id).joins(:elements => :purchase).where("purchases.completed_at not null").count
      if e == p
        true
      else
        false
      end
    end
  end
  
  def purchase_date
    
  end
  
  def self.make_estimate(type)
    @templates = Template.where(:name => 'Estimate',:type => type)
    @templates.each do |t|
      e = Element.create!(:estimate_id => self.id, :item_id => t.item_id, :quantity => t.quantity, :due_at => Time.now >> 1)
      e.save
    end
  end

  
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  def index
    @estimates = Estimate.all
  end

  def show
    @estimate = Estimate.find(params[:id])
    @elements = @estimate.elements.page(params[:page]).per_page(15)
    @fullvalue = @estimate.fullvalue
  end

  def new
    @estimate = Estimate.new
    @estimate.room_id = params[:room_id]
    @estimate.sale_id = params[:sale_id]
    #@estimate.elements.build
    @suppliers = Supplier.order("name")
  end

  def create
    if params[:estimate][:suppliers]
      params[:estimate].delete :suppliers    
    end
    puts params
    @estimate = Estimate.new(params[:estimate])
    if @estimate.save!
      redirect_to @estimate.room, :notice => "Successfully created estimate."
    else
      render :new
    end
  end

  def edit
    @estimate = Estimate.find(params[:id])
    @elements = @estimate.elements
  end

  def update
    @estimate = Estimate.find(params[:id])
    if @estimate.update_attributes(params[:estimate])
      redirect_to @estimate.room, :notice  => "Successfully updated estimate."
    else
      render :edit
    end
  end

  def destroy
    @estimate = Estimate.find(params[:id])
    @room = @estimate.room
    @estimate.destroy
    redirect_to @room, :notice => "Successfully destroyed estimate."
  end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_estimate.html.erb
<% present estimate,EstimatePresenter do |estimate_presenter| %>
    <tr>
      <td><%= link_to estimate.name, estimate_path(estimate) %></td>
      <td><%= estimate.room.name %></td>
      <td><%= estimate_presenter.quantities %></td>
      <td><%= ihelper estimate.value %></td>
      <td><%= ihelper estimate.purchase_date %></td>
      <td><%= ihelper estimate.fullvalue[1] %></td>
      <td><%= ihelper estimate_presenter.sale_created_at %></td>
      <td><%= ihelper estimate_presenter.sale_value %></td>
      <td><%= estimate_presenter.actions %></td>
    </tr>
<% end %>

app/views/estimates/_estimate_footer.html.erb
</tbody>
</table>

app/views/estimates/_estimate_titles.html.erb
<table class="table table-bordered table-stripped table-condensed" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Room</th>
      <th>Items</th>
      <th>Estimate Value</th>
      <th>Purchase Date</th>
      <th>Purchase Value</th>
      <th>Sale Date</th>
      <th>Sale Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

app/views/estimates/_form.html.erb
<%= simple_nested_form_for @estimate, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Estimate</legend>

    <%= f.input :name %>
    <%= f.association :room %>
    <!--<%= f.input :sale_id %>-->
    <%= f.fields_for :elements do |element_form| %>
      <%= f.simple_fields_for :suppliers , :html => {:class => 'control-group select'} do |simple| %>
        <div class="control-group select">
        <%= simple.label "Supplier" %>
          <div class="controls" >
            <%= simple.collection_select :supplier_id, Supplier.order(:name), :id, :name %>
          </div>
        </div>
      <% end %>
      <%= element_form.association :item, :collection => @suppliers, :as => :grouped_select, :group_method => :items %>
      <%= element_form.input :quantity %>
      <!--<%= element_form.input :due_at, :as => :date, :value => 30.days.from_now %>-->
      <%= element_form.link_to_remove "Remove Item" %>
    <% end %>
    <%= f.link_to_add "Add Item", :elements %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', estimates_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/estimates/_form_fields.html.erb
  <div class="field subform">
    <%= f.text_field :name %>
  </div>
  <div class="field subform">
    <%= f.collection_select(:room_id,Room.all, :id, :name ) %>
  </div>
  <div class="field subform">
    <%= f.collection_select(:sale_id,Sale.all, :id, :name ) %>
  </div>
  <div class="actions subform"><%= f.link_to_remove "Remove" %></div>
<% end %>

app/views/estimates/_form_fields_titles.html.erb
  <div class="field titles">
    <%= f.label :name %>
  </div>
  <div class="field titles">
    <%= f.label :room %>
  </div>
  <div class="field titles">
    <%= f.label :sale %>
  </div>

app/views/estimates/edit.html.erb
<%= render :partial => 'form' %>

app/views/estimates/index.html.erb
<h1>Estimates</h1>

<%= render "estimates/estimate_titles" %>
    <% @estimates.each do |estimate| %>
      <%= render estimate %> 
    <% end %>
<%= render "estimates/estimate_footer" %>

<%= link_to 'New', new_estimate_path, :class => 'btn btn-primary' %>

app/views/estimates/new.html.erb
<%= render :partial => 'form' %>

app/views/estimates/show.html.erb
<h1>Estimate</h1>

<p>
  <b>Name</b><br>
  <%= @estimate.name %>
</p>

<p>
  <b>Job/Room</b><br>
  <%= @estimate.room.job.client.name %> / <%= @estimate.room.job.name %> / <%= @estimate.room.name %>
</p>

<p>
  <b>Sale</b><br>
  <%= @estimate.sale_id %>
</p>

<p>
  <b>Value</b><br>
  <%= ihelper @estimate.value %>
</p>


<h2>Elements</h2>
<%= page_navigation_links @elements %>

<%= render "elements/element_titles" %>
    <% @elements.each do |element| %>
      <%= render element %>
    <% end %>
<%= render "elements/element_footer" %>

<%= link_to 'Add Item', new_element_path(:estimate_id => @estimate.id), :class => 'btn btn-primary' %>

<div class="form-actions">
  <%= link_to 'Back', room_path(@estimate.room), :class => 'btn'  %>
  <%= link_to 'Edit', edit_estimate_path(@estimate), :class => 'btn' %>
  <%= link_to 'Delete', estimate_path(@estimate), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>