config/routes.rb
WellerInteriorDesign::Application.routes.draw do
  resources :templates

  resources :timesheets

  resources :invoices

  resources :purchaseorders

  resources :sales

  resources :purchases

  resources :elements

  resources :estimates

  resources :rooms

  resources :jobs

  resources :clients

  resources :items

  resources :suppliers

  resources :categories

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  
  root :to => 'sessions#new', :as => :login

end

app/models/job.rb
class Job < ActiveRecord::Base

  attr_accessible :name, :address, :client_id, :markup
  
  
  belongs_to :client
  
  has_many :rooms
  accepts_nested_attributes_for :rooms
  
  has_many :invoices
  accepts_nested_attributes_for :invoices
  
  def value
    v = [0,0]
    self.rooms.each do |room|
      evalue = room.value
      v[0] += evalue[0]
      v[1] += evalue[1]
    end
    v
  end
  
  def fullvalue
    v = [[0,0],[0,0],[0,0]]
    self.rooms.each do |room|
      fvalue = room.fullvalue
      v[0][0] += fvalue[0][0]
      v[0][1] += fvalue[0][1]
      v[1][0] += fvalue[1][0]
      v[1][1] += fvalue[1][1]
      v[2][0] += fvalue[2][0]
      v[2][1] += fvalue[2][1]
    end
    v
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.order("name").page(params[:page]).per_page(10)
  end

  def show
    @job = Job.find(params[:id])
    @rooms = @job.rooms
    @fullvalue = @job.fullvalue
  end

  def new
    @job = Job.new
        @job.client_id = params[:client_id]
  end

  def create
    @job = Job.new(params[:job])
    if @job.save
      redirect_to @job.client, :notice => "Successfully created job."
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      redirect_to @job.client, :notice  => "Successfully updated job."
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_url, :notice => "Successfully destroyed job."
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Job</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :address, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :client_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :client_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :markup, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :markup, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', jobs_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/jobs/_form_fields.html.erb
  <div class="field subform">
    <%= f.text_field :name %>
  </div>
  <div class="field subform">
    <%= f.text_area :address %>
  </div>
  <div class="field subform">
    <%= f.collection_select(:client_id,Client.all, :id, :name ) %>
  </div>
  <div class="field subform">
    <%= f.text_field :markup %>
  </div>
  <div class="actions subform"><%= f.link_to_remove "Remove" %></div>
<% end %>

app/views/jobs/_form_fields_titles.html.erb
  <div class="field titles">
    <%= f.label :name %>
  </div>
  <div class="field titles">
    <%= f.label :address %>
  </div>
  <div class="field titles">
    <%= f.label :client %>
  </div>
  <div class="field titles">
    <%= f.label :markup %>
  </div>

app/views/jobs/_job.html.erb
    <tr>
      <td><%= link_to job.name, job_path(job) %></td>
      <td><%= job.address %></td>
      <td><%= job.client.name %></td>
      <td><%= job.rooms.count %></td>
      <td><%= job.invoices.count %></td>
      <td><%= job.markup %></td>
        <td>
          <%= link_to 'Edit', edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', job_path(job), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
     </tr>

app/views/jobs/_job_footer.html.erb
</tbody>
</table>

app/views/jobs/_job_titles.html.erb
<table class="table table-bordered table-stripped table-condensed" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Client</th>
      <th>Rooms</th>
      <th>Invoices</th>
      <th>Markup</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

app/views/jobs/edit.html.erb
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<%= page_navigation_links @jobs %>

<%= render "jobs/job_titles" %>
    <% @jobs.each do |job| %>
      <%= render job %>
    <% end %>
<%= render "jobs/job_footer" %>


<%= link_to 'New', new_job_path, :class => 'btn btn-primary' %>

app/views/jobs/new.html.erb
<%= render :partial => 'form' %>

app/views/jobs/show.html.erb
<h1>Job</h1>

<p>
  <b>Name</b><br>
  <%= @job.name %>
</p>

<p>
  <b>Address</b><br>
  <%= @job.address %>
</p>

<p>
  <b>Client</b><br>
  <%= @job.client_id %>
</p>

<p>
  <b>Markup</b><br>
  <%= @job.markup %>
</p>

<table class="table table-bordered table-stripped table-condensed" >
  <thead>
    <tr>
      <th>Job Value</th>
      <th>Estimate Value</th>
      <th>Purchase Value</th>
      <th>Sale Value</th>
      <th>Invoice Value</th>
    </tr>
  </thead>
  <tbody>
  <tr><td>Excluding VAT</td><td><%= ihelper @fullvalue[0][0] %></td><td><%= ihelper @fullvalue[1][0] %></td><td><%= ihelper @fullvalue[2][0] %></td><td><%= ihelper 0.00 %></td></tr>
  <tr><td>Including VAT</td><td><%= ihelper @fullvalue[0][1] %></td><td><%= ihelper @fullvalue[1][1] %></td><td><%=ihelper @fullvalue[2][1] %></td><td><%= ihelper 0.00 %></td></tr>
  </tbody>
  </table>



<h2>Rooms</h2>

<%= render "rooms/room_titles" %>
    <% @rooms.each do |room| %>
      <%= render room %>
    <% end %>
<%= render "rooms/room_footer" %>

<%= link_to 'New room', new_room_path(:job_id => @job.id), :class => 'btn' %>

<div class="form-actions">
  <%= link_to 'Back', @job.client, :class => 'btn'  %>
  <%= link_to 'Edit', edit_job_path(@job), :class => 'btn' %>
  <%= link_to 'Delete', job_path(@job), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>