config/routes.rb
WellerInteriorDesign::Application.routes.draw do
  resources :templates

  resources :timesheets

  resources :invoices

  resources :purchaseorders

  resources :sales

  resources :purchases

  resources :elements

  resources :estimates

  resources :rooms

  resources :jobs

  resources :clients

  resources :items

  resources :suppliers

  resources :categories

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  
  root :to => 'sessions#new', :as => :login

end

app/models/room.rb
class Room < ActiveRecord::Base

  attr_accessible :name, :job_id, :width, :length, :height, :windows
  
  belongs_to :job
  
  has_many :estimates
  validates_presence_of :name, :job_id
  
  def value
    v = [0,0]
    self.estimates.each do |estimate|
      evalue = estimate.value
      v[0] += evalue[0]
      v[1] += evalue[1]
    end
    v
  end

  def fullvalue
    v = [[0,0],[0,0],[0,0]]
    self.estimates.each do |estimate|
      fvalue = estimate.fullvalue
      v[0][0] += fvalue[0][0]
      v[0][1] += fvalue[0][1]
      v[1][0] += fvalue[1][0]
      v[1][1] += fvalue[1][1]
      v[2][0] += fvalue[2][0]
      v[2][1] += fvalue[2][1]
    end
    v
  end

  def started
    self.estimates.each do |estimate|
      if estimate.started
        return true
      end
    end
    return false
  end

  def self.make_estimate
    @templates = Template.where(:name => 'Room')
    @templates.each do |t|
      es = Estimate.create!(:room_id => self.id, :name => t.type)
      es.save
      es.make_estimate(t.subtype)
    end
  end

  accepts_nested_attributes_for :estimates
  
  
  
  
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @estimates = @room.estimates
  end

  def new
    @room = Room.new
    @room.job_id = params[:job_id]
  end

  def create
    @room = Room.new(params[:room])
    if @room.save
      redirect_to @room.job, :notice => "Successfully created room."
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(params[:room])
      redirect_to @room.job, :notice  => "Successfully updated room."
    else
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_url, :notice => "Successfully destroyed room."
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Room</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :job_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :job_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :width, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :width, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :length, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :length, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :height, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :height, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :windows, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :windows, :class => 'number_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', rooms_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/rooms/_form_fields.html.erb
  <div class="field subform">
    <%= f.text_field :name %>
  </div>
  <div class="field subform">
    <%= f.collection_select(:job_id,Job.all, :id, :name ) %>
  </div>
  <div class="field subform">
    <%= f.text_field :width %>
  </div>
  <div class="field subform">
    <%= f.text_field :length %>
  </div>
  <div class="field subform">
    <%= f.text_field :height %>
  </div>
  <div class="field subform">
    <%= f.number_field :windows %>
  </div>
  <div class="actions subform"><%= f.link_to_remove "Remove" %></div>
<% end %>

app/views/rooms/_form_fields_titles.html.erb
  <div class="field titles">
    <%= f.label :name %>
  </div>
  <div class="field titles">
    <%= f.label :job %>
  </div>
  <div class="field titles">
    <%= f.label :width %>
  </div>
  <div class="field titles">
    <%= f.label :length %>
  </div>
  <div class="field titles">
    <%= f.label :height %>
  </div>
  <div class="field titles">
    <%= f.label :windows %>
  </div>

app/views/rooms/_room.html.erb
<% present room,RoomPresenter do |room_presenter| %>
    <tr>
      <td><%= link_to room.name, room_path(room) %></td>
      <td><%= room.job.name %></td>
      <td><%= room_presenter.value %></td>
      <td><%= room.estimates.count %></td>
      <td><%= room.width %></td>
      <td><%= room.length %></td>
      <td><%= room.height %></td>
      <td><%= room.windows %></td>
      <% if room.started %>
      <td>
          <%= link_to 'Edit', edit_room_path(room), :class => 'btn btn-mini' %>      
      </td>
      <% else %>
      <td>
          <%= link_to 'Edit', edit_room_path(room), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', room_path(room), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
      </td>
      <% end %>
    </tr>
<% end %>

app/views/rooms/_room_footer.html.erb
</tbody>
</table>

app/views/rooms/_room_titles.html.erb
<table class="table table-bordered table-stripped table-condensed" >
  <thead>
    <tr>
      <th>Name</th>
      <th>Job</th>
      <th>Value</th>
      <th>Estimates</th>
      <th>Width</th>
      <th>Length</th>
      <th>Height</th>
      <th>Windows</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

app/views/rooms/edit.html.erb
<%= render :partial => 'form' %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>
<%= render "rooms/room_titles" %>
    <% @rooms.each do |room| %>
    <%= render room %>
    <% end %>
<%= render "rooms/room_footer" %>
<%= link_to 'New', new_room_path, :class => 'btn btn-primary' %>

app/views/rooms/new.html.erb
<%= render :partial => 'form' %>

app/views/rooms/show.html.erb
<h1>Room</h1>

<%= render "rooms/room_titles" %>
<%= render @room %>
<%= render "rooms/room_footer" %>

<h2>Estimates</h2>

<%= render "estimates/estimate_titles" %>
    <% @estimates.each do |estimate| %>
      <%= render estimate %>
    <% end %>
<%= render "estimates/estimate_footer" %>

<%= link_to 'New estimate', new_estimate_path(:room_id => @room.id), :class => 'btn' %>

<div class="form-actions">
  <%= link_to 'Back', @room.job, :class => 'btn'  %>
  <%= link_to 'Edit', edit_room_path(@room), :class => 'btn' %>
  <%= link_to 'Delete', room_path(@room), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>