config/routes.rb
WellerInteriorDesign::Application.routes.draw do
  resources :templates

  resources :timesheets

  resources :invoices

  resources :purchaseorders

  resources :sales

  resources :purchases

  resources :elements

  resources :estimates

  resources :rooms

  resources :jobs

  resources :clients

  resources :items

  resources :suppliers

  resources :categories

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  
  root :to => 'sessions#new', :as => :login

end

app/models/sale.rb
class Sale < ActiveRecord::Base

  attr_accessible :quantity, :price_ex_vat, :price_inc_vat, :invoice_id
  has_one :estimate  
  belongs_to :invoice
  validates_presence_of :quantity, :price_ex_vat, :price_inc_vat
  def self.no_invoice
     @uninvoices = Sale.joins(:element => {:room => {:job => :client}}).joins(:element => :estimate).where(:estimates => {:deleted_at => nil}).where(:sales => {:invoice_id => nil}).group(:jobs => :id).select("clients.name as clientname,jobs.name as jobname,jobs.id as job_id,count(*) as count_sales,sum(sales.quantity*sales.price_inc_vat) as value_sales")
  end
  
  def value
    [self.quantity*self.price_ex_vat,self.quantity*self.price_inc_vat]
  end
  
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @sales = Sale.all
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = Sale.new
    @sale.quantity = params[:quantity]
    @sale.price_ex_vat = params[:price_ex_vat].to_f.round(2)
    @sale.price_inc_vat = params[:price_inc_vat].to_f.round(2)
    @markup = params[:markup]
    @estimate = Estimate.find(params[:estimate_id])
    @purchase_price_ex_vat = params[:purchase_price_ex_vat]
    @purchase_price_inc_vat = params[:purchase_price_inc_vat]
    session[:estimate_id] = params[:estimate_id]
  end

  def create
    if params[:sale][:markup]
      params[:sale].delete :markup
    end
    @sale = Sale.new(params[:sale])
    if @sale.save
      if session[:estimate_id]
        @estimate = Estimate.find(session[:estimate_id])
        @estimate.update_attributes(:sale_id => @sale.id)
        session[:estimate_id] = nil
      end
      redirect_to @estimate.room, :notice => "Successfully created sale."
    else
      render :new
    end
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    @sale = Sale.find(params[:id])
    if @sale.update_attributes(params[:sale])
      redirect_to sales_url, :notice  => "Successfully updated sale."
    else
      render :edit
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    redirect_to sales_url, :notice => "Successfully destroyed sale."
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for @sale, :html => { :class => 'form-horizontal' } do |f| %>
    <legend><%= controller.action_name.capitalize %> Sale</legend>

    <%= render 'estimates/estimate_titles' %>
    <%= render @estimate %>
    <%= render 'estimates/estimate_footer' %>
    <p>Purchase Price</p>
    <div id="purchase_price_ex_vat"><%= ihelper @purchase_price_ex_vat %></div>
    <div id="purchase_price_inc_vat"><%= ihelper @purchase_price_inc_vat %></div>
  <fieldset>

    <%= f.input :quantity %>
    <div class="control-group decimal optional">
    <%= f.label :markup %>
    <div class="controls">
    <%= f.input_field :markup, :value => @markup %>
    </div>
    </div>
    <%= f.input :price_ex_vat, :as => :currency, :input_html => { :size => 10 } %>
    <%= f.input :price_inc_vat, :as => :currency%>
    

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', sales_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/sales/_form_fields.html.erb
  <div class="field subform">
    <%= f.text_field :quantity %>
  </div>
  <div class="field subform">
    <%= f.text_field :price_ex_vat %>
  </div>
  <div class="field subform">
    <%= f.text_field :price_inc_vat %>
  </div>
  <div class="field subform">
    <%= f.collection_select(:invoice_id,Invoice.all, :id, :name ) %>
  </div>
  <div class="actions subform"><%= f.link_to_remove "Remove" %></div>
<% end %>

app/views/sales/_form_fields_titles.html.erb
  <div class="field titles">
    <%= f.label :quantity %>
  </div>
  <div class="field titles">
    <%= f.label :price_ex_vat %>
  </div>
  <div class="field titles">
    <%= f.label :price_inc_vat %>
  </div>
  <div class="field titles">
    <%= f.label :invoice %>
  </div>

app/views/sales/_sale.html.erb
    <tr>
      <td><%= sale.estimate %></td>
      <td><%= sale.quantity %></td>
      <td><%= sale.price_ex_vat %></td>
      <td><%= sale.price_inc_vat %></td>
      <td><%= sale.invoice.name %></td>
      <td><%= link_to "Edit", edit_sale_path(sale) %></td>
    </tr>

app/views/sales/_sale_footer.html.erb
</tbody>
</table>

app/views/sales/_sale_titles.html.erb
<table class="table table-bordered table-stripped table-condensed" >
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Price Ex Vat</th>
      <th>Price Inc Vat</th>
      <th>Invoice</th>
  
    </tr>
  </thead>
  <tbody>

app/views/sales/edit.html.erb
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<h1>Sales</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Quantity</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.id %></td>
        <td><%= link_to sale.quantity, sale_path(sale) %></td>
        <td><%= sale.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_sale_path(sale), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', sale_path(sale), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_sale_path, :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<h1>Sale</h1>

<p>
  <b>Quantity</b><br>
  <%= @sale.quantity %>
</p>

<p>
  <b>Price ex vat</b><br>
  <%= @sale.price_ex_vat %>
</p>

<p>
  <b>Price inc vat</b><br>
  <%= @sale.price_inc_vat %>
</p>

<p>
  <b>Invoice</b><br>
  <%= @sale.invoice_id %>
</p>

<div class="form-actions">
  <%= link_to 'Back', sales_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_sale_path(@sale), :class => 'btn' %>
  <%= link_to 'Delete', sale_path(@sale), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>